# Generated by Django 5.2.6 on 2025-10-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
