# Generated by Django 5.2.6 on 2025-10-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_post_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
