# Generated by Django 5.2.6 on 2025-10-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='timestamp',
        ),
    ]
