# Generated by Django 5.2.6 on 2025-10-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_postadd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postadd',
            name='sno',
        ),
        migrations.AddField(
            model_name='postadd',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
