# Generated by Django 5.2.6 on 2025-10-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_remove_postadd_sno_postadd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
